//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.UserMessage", typeof(UserMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השקים הבאים כבר נמצאים בשינוע פעיל: {0}.
        /// </summary>
        public static string ActiveTransport {
            get {
                return ResourceManager.GetString("ActiveTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אחד מפרטי ההזדהות אינם נכונים.
        /// </summary>
        public static string CerdError {
            get {
                return ResourceManager.GetString("CerdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חלל לא נמצא.
        /// </summary>
        public static string DeceasedNotExists {
            get {
                return ResourceManager.GetString("DeceasedNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיאה בעת ההזדהות.
        /// </summary>
        public static string ErrorAuth {
            get {
                return ResourceManager.GetString("ErrorAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיה בעת המחיקה.
        /// </summary>
        public static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שגיאת מערכת.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיאה בעת טעינת הנתונים.
        /// </summary>
        public static string ErrorLoadData {
            get {
                return ResourceManager.GetString("ErrorLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיאה בעת הפקת הדו&quot;ח.
        /// </summary>
        public static string ErrorLoadReport {
            get {
                return ResourceManager.GetString("ErrorLoadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיאה בעת השמירה.
        /// </summary>
        public static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארעה שגיאה אנא פנה למנהל מערכת.
        /// </summary>
        public static string ErrorSystem {
            get {
                return ResourceManager.GetString("ErrorSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קובץ לא קיים: {0} .
        /// </summary>
        public static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התיקייה לא קיימת: {0}.
        /// </summary>
        public static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הודעת מערכת.
        /// </summary>
        public static string InfoDialogTitle {
            get {
                return ResourceManager.GetString("InfoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לשנע יותר מ-2 חללים בבת אחת.
        /// </summary>
        public static string LimitDeceasedsInTransport {
            get {
                return ResourceManager.GetString("LimitDeceasedsInTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אינך רשאי לבצע פעולה זו.
        /// </summary>
        public static string NotAllowedAction {
            get {
                return ResourceManager.GetString("NotAllowedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר הפלאפון לא קיים במערכת. נא להתחבר בעזרת אימייל ולהוסיפו בפרופיל האישי.
        /// </summary>
        public static string PhoneNumberNotExists {
            get {
                return ResourceManager.GetString("PhoneNumberNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השמירה בוצעה בהצלחה.
        /// </summary>
        public static string SuccessSave {
            get {
                return ResourceManager.GetString("SuccessSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הבקשה נשלחה בהצלחה.
        /// </summary>
        public static string SuccessSendRequest {
            get {
                return ResourceManager.GetString("SuccessSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שינוע זה כבר הסתיים.
        /// </summary>
        public static string TransportIsComplete {
            get {
                return ResourceManager.GetString("TransportIsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יעד שינוע לא נתמך.
        /// </summary>
        public static string UnknownTransportDestination {
            get {
                return ResourceManager.GetString("UnknownTransportDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משתמש כבר קיים במועצה הזו.
        /// </summary>
        public static string UserMoatzaExist {
            get {
                return ResourceManager.GetString("UserMoatzaExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משתמש אינו קיים.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
    }
}
