<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Configurations>Debug;Release;Staging;Production</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="EFCore.BulkExtensions" Version="8.0.3"/>
        <PackageReference Include="Hangfire" Version="1.8.20"/>
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.20"/>
        <PackageReference Include="Hangfire.Core" Version="1.8.20"/>
        <PackageReference Include="Hangfire.SqlServer" Version="1.8.20"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\Core.csproj"/>
        <ProjectReference Include="..\DataModel\DataModel.csproj"/>
        <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
        <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.0"/>
        <PackageReference Include="System.ServiceModel.Federation" Version="8.0.0"/>
        <PackageReference Include="System.ServiceModel.Http" Version="8.0.0"/>
        <PackageReference Include="System.ServiceModel.NetTcp" Version="8.0.0"/>
        <PackageReference Include="System.ServiceModel.Security" Version="6.0.0"/>
    </ItemGroup>

</Project>
