name: Build and deploy Angular app to Azure Web App - burial-app-poc

on:
  push:
    branches:
      - task-1514-init-burial-app
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: WebApp
        run: npm install

      - name: Build Angular app
        working-directory: WebApp
        run: npm run build -- --configuration=production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: WebApp/dist/emergency-burial-app/browser

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-app
          path: ./angular-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CFC028C0A492417D9769E342B35380BA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C0EE1136EE3440799D06C17494D9E5B7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9F942BC0C3A3485194DE25421CBA97EA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'burial-app-poc'
          slot-name: 'Production'
          package: ./angular-app

